apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: sleeq-mongodb-pvc
  labels: 
    app: sleeq-mongodb
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi
