apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sleeq-mongodb
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: sleeq-mongodb
  template: 
    metadata: 
      labels: 
        app: sleeq-mongodb
    spec: 
      containers: 
        - 
          name: sleeq-mongodb
          image: arm64v8/mongo
          imagePullPolicy: Always
          env: 
            - name: "MONGO_INITDB_ROOT_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: sleeq-mongodb-secrets
                  key: username
              
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: sleeq-mongodb-secrets
                  key: password
              
          ports: 
            - 
              containerPort: 27017
              name: mongodb
              
          volumeMounts: 
            - 
              name: mongodb-persistent-storage
              mountPath: /data/db
              
      volumes: 
        - 
          name: mongodb-persistent-storage
          persistentVolumeClaim: 
            claimName: sleeq-mongodb-pvc