apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleeq-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleeq-api
  template:
    metadata:
      labels:
        app: sleeq-api
    spec:
      containers:
      - image: hdms241/apiserver:latest # {"$imagepolicy": "flux-system:sleeq-api"}
        imagePullPolicy: IfNotPresent
        name: sleeq-api
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: sleeq-api-creds
              key: port
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: sleeq-api-creds
              key: node_env
        - name: PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: sleeq-api-creds
              key: public_key
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: sleeq-api-creds
              key: private_key
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: sleeq-api-creds
              key: mongodb_url

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sleeq-api
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sleeq-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
