apiVersion: v1
kind: Service
metadata:
  name: sleeq-api-service
  labels:
    app: sleeq-api
spec:
  type: ClusterIP
  selector:
    app: sleeq-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
